// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"

	iface "github.com/adiom-data/dsync/protocol/iface"
	mock "github.com/stretchr/testify/mock"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

// GetConnectorStatus provides a mock function with given fields: flowId
func (_m *Connector) GetConnectorStatus(flowId iface.FlowID) iface.ConnectorStatus {
	ret := _m.Called(flowId)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectorStatus")
	}

	var r0 iface.ConnectorStatus
	if rf, ok := ret.Get(0).(func(iface.FlowID) iface.ConnectorStatus); ok {
		r0 = rf(flowId)
	} else {
		r0 = ret.Get(0).(iface.ConnectorStatus)
	}

	return r0
}

// IntegrityCheck provides a mock function with given fields: ctx, flowId, task
func (_m *Connector) IntegrityCheck(ctx context.Context, flowId iface.FlowID, task iface.ReadPlanTask) (iface.ConnectorDataIntegrityCheckResult, error) {
	ret := _m.Called(ctx, flowId, task)

	if len(ret) == 0 {
		panic("no return value specified for IntegrityCheck")
	}

	var r0 iface.ConnectorDataIntegrityCheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, iface.FlowID, iface.ReadPlanTask) (iface.ConnectorDataIntegrityCheckResult, error)); ok {
		return rf(ctx, flowId, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, iface.FlowID, iface.ReadPlanTask) iface.ConnectorDataIntegrityCheckResult); ok {
		r0 = rf(ctx, flowId, task)
	} else {
		r0 = ret.Get(0).(iface.ConnectorDataIntegrityCheckResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, iface.FlowID, iface.ReadPlanTask) error); ok {
		r1 = rf(ctx, flowId, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Interrupt provides a mock function with given fields: flowId
func (_m *Connector) Interrupt(flowId iface.FlowID) error {
	ret := _m.Called(flowId)

	if len(ret) == 0 {
		panic("no return value specified for Interrupt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(iface.FlowID) error); ok {
		r0 = rf(flowId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestCreateReadPlan provides a mock function with given fields: flowId, options
func (_m *Connector) RequestCreateReadPlan(flowId iface.FlowID, options iface.ConnectorOptions) error {
	ret := _m.Called(flowId, options)

	if len(ret) == 0 {
		panic("no return value specified for RequestCreateReadPlan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(iface.FlowID, iface.ConnectorOptions) error); ok {
		r0 = rf(flowId, options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetParameters provides a mock function with given fields: flowId, reqCap
func (_m *Connector) SetParameters(flowId iface.FlowID, reqCap iface.ConnectorCapabilities) {
	_m.Called(flowId, reqCap)
}

// Setup provides a mock function with given fields: ctx, t
func (_m *Connector) Setup(ctx context.Context, t iface.Transport) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Setup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, iface.Transport) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartReadToChannel provides a mock function with given fields: flowId, options, readPlan, dataChannel
func (_m *Connector) StartReadToChannel(flowId iface.FlowID, options iface.ConnectorOptions, readPlan iface.ConnectorReadPlan, dataChannel iface.DataChannelID) error {
	ret := _m.Called(flowId, options, readPlan, dataChannel)

	if len(ret) == 0 {
		panic("no return value specified for StartReadToChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(iface.FlowID, iface.ConnectorOptions, iface.ConnectorReadPlan, iface.DataChannelID) error); ok {
		r0 = rf(flowId, options, readPlan, dataChannel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartWriteFromChannel provides a mock function with given fields: flowId, dataChannel
func (_m *Connector) StartWriteFromChannel(flowId iface.FlowID, dataChannel iface.DataChannelID) error {
	ret := _m.Called(flowId, dataChannel)

	if len(ret) == 0 {
		panic("no return value specified for StartWriteFromChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(iface.FlowID, iface.DataChannelID) error); ok {
		r0 = rf(flowId, dataChannel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Teardown provides a mock function with given fields:
func (_m *Connector) Teardown() {
	_m.Called()
}

// NewConnector creates a new instance of Connector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connector {
	mock := &Connector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
