// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: adiom/v1/adiom.proto
// Protobuf Java Version: 4.29.1

package adiom.v1;

public final class Adiom {
  private Adiom() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      Adiom.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024adiom/v1/adiom.proto\022\010adiom.v1\032\027adiom/" +
      "v1/messages.proto2\374\004\n\020ConnectorService\022>" +
      "\n\007GetInfo\022\030.adiom.v1.GetInfoRequest\032\031.ad" +
      "iom.v1.GetInfoResponse\022e\n\024GetNamespaceMe" +
      "tadata\022%.adiom.v1.GetNamespaceMetadataRe" +
      "quest\032&.adiom.v1.GetNamespaceMetadataRes" +
      "ponse\022D\n\tWriteData\022\032.adiom.v1.WriteDataR" +
      "equest\032\033.adiom.v1.WriteDataResponse\022M\n\014W" +
      "riteUpdates\022\035.adiom.v1.WriteUpdatesReque" +
      "st\032\036.adiom.v1.WriteUpdatesResponse\022M\n\014Ge" +
      "neratePlan\022\035.adiom.v1.GeneratePlanReques" +
      "t\032\036.adiom.v1.GeneratePlanResponse\022A\n\010Lis" +
      "tData\022\031.adiom.v1.ListDataRequest\032\032.adiom" +
      ".v1.ListDataResponse\022R\n\rStreamUpdates\022\036." +
      "adiom.v1.StreamUpdatesRequest\032\037.adiom.v1" +
      ".StreamUpdatesResponse0\001\022F\n\tStreamLSN\022\032." +
      "adiom.v1.StreamLSNRequest\032\033.adiom.v1.Str" +
      "eamLSNResponse0\0012\274\001\n\020TransformService\022Y\n" +
      "\020GetTransformInfo\022!.adiom.v1.GetTransfor" +
      "mInfoRequest\032\".adiom.v1.GetTransformInfo" +
      "Response\022M\n\014GetTransform\022\035.adiom.v1.GetT" +
      "ransformRequest\032\036.adiom.v1.GetTransformR" +
      "esponseB2Z0github.com/adiom-data/dsync/g" +
      "en/adiom/v1;adiomv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          adiom.v1.Messages.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    adiom.v1.Messages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
