name: Build and Release

# Trigger on push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Ensuring the GITHUB_TOKEN has write permissions to contents

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get the latest tag name and increment it
      id: get_tag_name
      run: |
        TAG=$(git ls-remote --tags origin=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag found: $TAG"
        if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          IFS='.' read -r -a parts <<< "${TAG:1}"
          new_version="v${parts[0]}.${parts[1]}.$((parts[2]+1))"
        else
          new_version="v0.0.1"
        fi
        echo "NEW_TAG=$new_version" >> $GITHUB_ENV
