name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Cosmos
      run: COSMOS_TEST_DB=testci COSMOS_TEST_COL=testcicol COSMOS_TEST="${{ secrets.COSMOS_TEST }}" go test -run TestCosmosConnectorSuite -count=1 -v --tags=external github.com/adiom-data/dsync/connectors/cosmos

    - name: Mongo
      run: MONGO_TEST=mongodb://34.133.93.148:27027 go test -count=1 -v --tags=external github.com/adiom-data/dsync/connectors/mongo